In [1]:
from sagas.ofbiz.entities import OfEntity as e, format
# 先删除已经创建的PaymentApplication, 否则无法测试
e().removePaymentApplication(billingAccountId='appltest10000')

6

In [1]:
from sagas.ofbiz.entities import OfEntity as e, format
e('df').queryPaymentApplication(billingAccountId='appltest10000')

,lastUpdatedStamp,amountApplied,createdTxStamp,createdStamp,lastUpdatedTxStamp,billingAccountId,paymentApplicationId,paymentId
0,2019-02-13 00:58:51.199,20.0,2019-02-13 00:58:51.164,2019-02-13 00:58:51.199,2019-02-13 00:58:51.164,appltest10000,10009,appltest10000

In [8]:
from sagas.ofbiz.entities import OfEntity as e, format
billingAccountId='appltest10000'
rs=e().queryPaymentApplication(billingAccountId=billingAccountId)
if len(rs)>0:
    val=rs[0]
    ret=e.remove(val)
    print(ret)
else:
    print('no payment appl for', billingAccountId)

None

In [7]:
from sagas.ofbiz.services import OfService as s, oc, track
from sagas.ofbiz.entities import OfEntity as e, format

# testBillingAppl
ok,r=s().createPaymentApplication(paymentId='appltest10000',
    billingAccountId='appltest10000')
print(ok, r)

True {'paymentTypeId': 'CUSTOMER_PAYMENT', 'paymentApplicationId': '10010', 'responseMessage': 'success', 'amountApplied': Decimal('20.00')}

In [4]:
print(r['amountApplied'], r['paymentApplicationId'])
paymentApplication=e().getPaymentApplication(paymentApplicationId=r['paymentApplicationId'])
format(paymentApplication)

20.00 10006
+----------------------+-------------------------+
| name                 | value                   |
|----------------------+-------------------------|
| lastUpdatedStamp     | 2019-02-13 00:42:05.681 |
| toPaymentId          |                         |
| amountApplied        | 20.00                   |
| createdTxStamp       | 2019-02-13 00:42:05.654 |
| createdStamp         | 2019-02-13 00:42:05.681 |
| overrideGlAccountId  |                         |
| lastUpdatedTxStamp   | 2019-02-13 00:42:05.654 |
| invoiceItemSeqId     |                         |
| billingAccountId     | appltest10000           |
| paymentApplicationId | 10006                   |
| paymentId            | appltest10000           |
| taxAuthGeoId         |                         |
| invoiceId            |                         |
+----------------------+-------------------------+

In [5]:
oc.import_package('org.apache.ofbiz.accounting.payment.PaymentWorker')
oc.j.PaymentWorker.getPaymentNotApplied(oc.delegator, 'appltest10000')

Decimal('0.00')

In [6]:
format(e().refPayment('appltest10000'))

+--------------------------+-------------------------+
| name                     | value                   |
|--------------------------+-------------------------|
| roleTypeIdTo             |                         |
| finAccountTransId        |                         |
| partyIdFrom              | DemoCustomer            |
| lastUpdatedStamp         | 2019-02-12 23:17:57.536 |
| amount                   | 20.00                   |
| paymentPreferenceId      |                         |
| comments                 |                         |
| createdTxStamp           | 2019-02-12 19:23:59.351 |
| actualCurrencyAmount     |                         |
| createdStamp             | 2019-02-12 19:23:59.379 |
| overrideGlAccountId      |                         |
| lastUpdatedTxStamp       | 2019-02-12 23:17:57.53  |
| paymentMethodTypeId      | EFT_ACCOUNT             |
| actualCurrencyUomId      |                         |
| paymentTypeId            | CUSTOMER_PAYMENT        |
| currencyUomId            | USD                     |
| statusId                 | PMNT_NOT_PAID           |
| paymentId                | appltest10000           |
| paymentMethodId          |                         |
| paymentGatewayResponseId |                         |
| paymentRefNum            |                         |
| partyIdTo                | Company                 |
| effectiveDate            | 2006-04-25 12:56:54.292 |
+--------------------------+-------------------------+

In [7]:
print(paymentApplication['billingAccountId'])
print(paymentApplication['paymentId'])
print(paymentApplication['amountApplied'])

appltest10000
appltest10000
20.00

In [20]:
e('meta').PaymentApplication

                    name primary             type       field type
0   paymentApplicationId       *               id               id
1              paymentId                       id               id
2              invoiceId                       id               id
3       invoiceItemSeqId                       id               id
4       billingAccountId                       id               id
5    overrideGlAccountId                       id               id
6            toPaymentId                       id               id
7           taxAuthGeoId                       id               id
8          amountApplied          currency-amount  currency-amount
9       lastUpdatedStamp                date-time        date-time
10    lastUpdatedTxStamp                date-time        date-time
11          createdStamp                date-time        date-time
12        createdTxStamp                date-time        date-time

In [8]:
e('df').queryPaymentApplication(billingAccountId='appltest10000')

,lastUpdatedStamp,amountApplied,createdTxStamp,createdStamp,lastUpdatedTxStamp,billingAccountId,paymentApplicationId,paymentId
0,2019-02-13 00:42:05.681,20.0,2019-02-13 00:42:05.654,2019-02-13 00:42:05.681,2019-02-13 00:42:05.654,appltest10000,10006,appltest10000

In [9]:
notAppliedPayment=oc.j.PaymentWorker.getPaymentNotApplied(oc.delegator, 'appltest10000')
billingAccount=e().refBillingAccount("appltest10000")
format(billingAccount)

+----------------------+---------------------------------------+
| name                 | value                                 |
|----------------------+---------------------------------------|
| fromDate             | 2001-05-13 00:00:00.0                 |
| lastUpdatedStamp     | 2019-02-12 23:17:57.539               |
| accountLimit         | 10000.00                              |
| externalAccountId    |                                       |
| accountCurrencyUomId | USD                                   |
| createdTxStamp       | 2019-02-12 19:23:59.351               |
| createdStamp         | 2019-02-12 19:23:59.388               |
| description          | Demo Customer Company Billing Account |
| lastUpdatedTxStamp   | 2019-02-12 23:17:57.53                |
| billingAccountId     | appltest10000                         |
| contactMechId        | 9010                                  |
| thruDate             |                                       |
+----------------------+---------------------------------------+

In [23]:
e('meta').BillingAccount

                    name primary             type       field type
0       billingAccountId       *               id               id
1           accountLimit          currency-amount  currency-amount
2   accountCurrencyUomId                       id               id
3          contactMechId                       id               id
4               fromDate                date-time        date-time
5               thruDate                date-time        date-time
6            description              description      description
7      externalAccountId                       id               id
8       lastUpdatedStamp                date-time        date-time
9     lastUpdatedTxStamp                date-time        date-time
10          createdStamp                date-time        date-time
11        createdTxStamp                date-time        date-time

In [10]:
# 计算结算帐户的“可用”余额，即净余额减去待处理（未取消，已拒收或已接收）订单付款的金额。
# 在查看使用结算帐户查看新订单时，您应该使用此方法。
oc.import_package('org.apache.ofbiz.order.order.OrderReadHelper')
appliedBillling=oc.j.OrderReadHelper.getBillingAccountBalance(billingAccount)
print(appliedBillling)

10020.00

In [11]:
print(notAppliedPayment)

0.00

In [12]:
e('df').queryPayment(paymentId='appltest10000')

,partyIdFrom,lastUpdatedStamp,amount,createdTxStamp,createdStamp,lastUpdatedTxStamp,paymentMethodTypeId,paymentTypeId,currencyUomId,statusId,paymentId,partyIdTo,effectiveDate
0,DemoCustomer,2019-02-12 23:17:57.536,20.0,2019-02-12 19:23:59.351,2019-02-12 19:23:59.379,2019-02-12 23:17:57.530,EFT_ACCOUNT,CUSTOMER_PAYMENT,USD,PMNT_NOT_PAID,appltest10000,Company,2006-04-25 12:56:54.292

In [13]:
e('df').allPayment()

,finAccountTransId,partyIdFrom,lastUpdatedStamp,amount,paymentPreferenceId,createdTxStamp,actualCurrencyAmount,createdStamp,lastUpdatedTxStamp,paymentMethodTypeId,actualCurrencyUomId,paymentTypeId,currencyUomId,statusId,paymentId,paymentMethodId,paymentGatewayResponseId,paymentRefNum,partyIdTo,effectiveDate
0,None,Company,2019-01-26 21:09:21.143,70.00,None,2019-01-26 21:09:19.636,70.00,2019-01-26 21:09:21.143,2019-01-26 21:09:19.636,EXT_BILLACT,USD,VENDOR_PAYMENT,USD,PMNT_SENT,8000,None,None,None,AcctBigSupplier,2009-07-06 16:52:52.901
1,9102,Company,2019-01-26 21:09:21.536,82.86,None,2019-01-26 21:09:19.636,NaN,2019-01-26 21:09:21.165,2019-01-26 21:09:19.636,COMPANY_CHECK,None,VENDOR_PAYMENT,USD,PMNT_SENT,8001,None,None,"100,100",AcctBigSupplier,2009-07-11 12:28:44.034
2,9104,Company,2019-01-26 21:09:21.542,33.99,None,2019-01-26 21:09:19.636,NaN,2019-01-26 21:09:21.166,2019-01-26 21:09:19.636,COMPANY_CHECK,None,VENDOR_PAYMENT,USD,PMNT_SENT,8002,None,None,"100,101",DemoSupplier,2009-07-11 12:28:44.950
3,9103,AcctBuyer,2019-01-26 21:09:21.539,20.00,None,2019-01-26 21:09:19.636,20.00,2019-01-26 21:09:21.418,2019-01-26 21:09:19.636,COMPANY_CHECK,USD,CUSTOMER_PAYMENT,USD,PMNT_RECEIVED,8003,None,None,None,Company,2009-08-12 16:33:34.922
4,None,DemoCustomer,2019-01-26 21:09:31.115,127.09,9001,2019-01-26 21:09:22.215,NaN,2019-01-26 21:09:31.115,2019-01-26 21:09:22.215,CREDIT_CARD,None,CUSTOMER_PAYMENT,USD,PMNT_RECEIVED,8004,9015,9002,1250501224763,Company,2009-08-17 14:57:04.990
5,None,Company,2019-01-26 21:09:30.894,190.97,None,2019-01-26 21:09:22.215,NaN,2019-01-26 21:09:30.894,2019-01-26 21:09:22.215,EFT_ACCOUNT,None,VENDOR_PAYMENT,USD,PMNT_NOT_PAID,9000,SC_CHECKING,None,None,DemoSupplier,2006-04-25 12:56:54.292
6,None,DemoCustomer,2019-02-12 23:17:57.536,20.00,None,2019-02-12 19:23:59.351,NaN,2019-02-12 19:23:59.379,2019-02-12 23:17:57.530,EFT_ACCOUNT,None,CUSTOMER_PAYMENT,USD,PMNT_NOT_PAID,appltest10000,None,None,None,Company,2006-04-25 12:56:54.292
7,None,Company,2019-02-12 23:17:57.578,20.00,None,2019-02-12 19:23:59.351,NaN,2019-02-12 19:23:59.400,2019-02-12 23:17:57.530,EFT_ACCOUNT,None,CUSTOMER_REFUND,USD,PMNT_NOT_PAID,appltest10001,None,None,None,DemoCustomer,2006-04-25 12:56:54.292
8,None,Company,2019-02-12 23:17:57.580,20.00,None,2019-02-12 19:23:59.351,NaN,2019-02-12 19:23:59.403,2019-02-12 23:17:57.530,EFT_ACCOUNT,None,SALES_TAX_PAYMENT,USD,PMNT_NOT_PAID,appltest10002,None,None,None,USA_IRS,2006-04-25 12:56:54.292
9,None,AcctBuyer,2019-01-26 21:09:21.109,190.97,None,2019-01-26 21:09:19.636,NaN,2019-01-26 21:09:21.109,2019-01-26 21:09:19.636,EFT_ACCOUNT,None,CUSTOMER_PAYMENT,USD,PMNT_NOT_PAID,demo10000,None,None,None,Company,2006-04-25 12:56:54.292
10,None,EuroCustomer,2019-01-26 21:09:21.134,820.97,None,2019-01-26 21:09:19.636,543.23,2019-01-26 21:09:21.134,2019-01-26 21:09:19.636,EFT_ACCOUNT,EUR,CUSTOMER_PAYMENT,USD,PMNT_RECEIVED,demo10001,None,None,None,Company,2006-04-25 12:56:54.292
11,None,Company,2019-01-26 21:09:21.110,20.00,None,2019-01-26 21:09:19.636,NaN,2019-01-26 21:09:21.110,2019-01-26 21:09:19.636,EXT_BILLACT,None,CUSTOMER_REFUND,USD,PMNT_SENT,demo10010,None,None,None,AcctBuyer,2006-04-25 13:11:05.940

## testInvoiceAppl
test the application of a payment against an invoice

In [15]:
# 先删除已经创建的PaymentApplication, 否则无法测试
e().removePaymentApplication(billingAccountId='appltest10000')

1

In [9]:
e('meta').Invoice

                  name primary           type     field type
0            invoiceId       *             id             id
1        invoiceTypeId                     id             id
2          partyIdFrom                     id             id
3              partyId                     id             id
4           roleTypeId                     id             id
5             statusId                     id             id
6     billingAccountId                     id             id
7        contactMechId                     id             id
8          invoiceDate              date-time      date-time
9              dueDate              date-time      date-time
10            paidDate              date-time      date-time
11      invoiceMessage           long-varchar   long-varchar
12     referenceNumber          short-varchar  short-varchar
13         description            description    description
14       currencyUomId                     id             id
15    recurrenceInfoId                     id             id
16    lastUpdatedStamp              date-time      date-time
17  lastUpdatedTxStamp              date-time      date-time
18        createdStamp              date-time      date-time
19      createdTxStamp              date-time      date-time

In [10]:
e('df').allInvoice()

,partyIdFrom,lastUpdatedStamp,createdTxStamp,invoiceTypeId,dueDate,createdStamp,description,lastUpdatedTxStamp,invoiceDate,currencyUomId,statusId,paidDate,invoiceId,partyId
0,DEMO_COMPANY,2019-02-12 19:23:59.307,2019-02-12 19:23:58.705,PURCHASE_INVOICE,NaT,2019-02-12 19:23:59.307,None,2019-02-12 19:23:58.705,2016-11-03 00:00:00.000,None,None,NaT,1000,DEMO_COMPANY1
1,DEMO_COMPANY,2019-02-12 19:24:08.012,2019-02-12 19:24:07.711,PURCHASE_INVOICE,NaT,2019-02-12 19:24:08.012,None,2019-02-12 19:24:07.711,2019-02-12 19:24:07.707,None,INVOICE_IN_PROCESS,NaT,10001,DEMO_COMPANY1
2,DEMO_COMPANY,2019-02-12 19:23:59.310,2019-02-12 19:23:58.705,PURCHASE_INVOICE,NaT,2019-02-12 19:23:59.310,None,2019-02-12 19:23:58.705,2016-11-03 00:00:00.000,None,None,NaT,1001,DEMO_COMPANY1
3,DEMO_COMPANY,2019-02-12 23:17:57.512,2019-02-12 19:23:58.705,PURCHASE_INVOICE,NaT,2019-02-12 19:23:59.324,None,2019-02-12 23:17:57.291,2016-11-03 00:00:00.000,None,INVOICE_IN_PROCESS,NaT,1002,DEMO_COMPANY1
4,DEMO_COMPANY,2019-02-12 19:23:59.330,2019-02-12 19:23:58.705,PURCHASE_INVOICE,NaT,2019-02-12 19:23:59.330,None,2019-02-12 19:23:58.705,2016-11-03 00:00:00.000,None,INVOICE_IN_PROCESS,NaT,1003,DEMO_COMPANY1
5,DEMO_COMPANY,2019-02-12 19:23:59.332,2019-02-12 19:23:58.705,PURCHASE_INVOICE,NaT,2019-02-12 19:23:59.332,None,2019-02-12 19:23:58.705,2016-11-03 00:00:00.000,None,None,NaT,1004,DEMO_COMPANY1
6,DEMO_COMPANY,2019-02-12 19:23:59.335,2019-02-12 19:23:58.705,PURCHASE_INVOICE,NaT,2019-02-12 19:23:59.335,None,2019-02-12 19:23:58.705,2016-11-03 00:00:00.000,None,INVOICE_IN_PROCESS,NaT,1005,DEMO_COMPANY1
7,DEMO_COMPANY,2019-02-12 19:23:59.337,2019-02-12 19:23:58.705,PURCHASE_INVOICE,NaT,2019-02-12 19:23:59.337,None,2019-02-12 19:23:58.705,2016-11-03 00:00:00.000,None,INVOICE_IN_PROCESS,NaT,1006,DEMO_COMPANY1
8,DEMO_COMPANY,2019-02-12 19:23:59.343,2019-02-12 19:23:58.705,PURCHASE_INVOICE,NaT,2019-02-12 19:23:59.343,None,2019-02-12 19:23:58.705,2016-11-03 00:00:00.000,None,INVOICE_IN_PROCESS,NaT,1007,DEMO_COMPANY1
9,AcctBigSupplier,2019-01-26 21:09:21.141,2019-01-26 21:09:19.636,PURCHASE_INVOICE,2009-08-05 16:48:40.952,2019-01-26 21:09:21.141,None,2019-01-26 21:09:19.636,2009-07-06 16:48:40.952,USD,INVOICE_READY,2009-07-06 16:52:52.901,8000,Company
10,AcctBigSupplier,2019-01-26 21:09:21.145,2019-01-26 21:09:19.636,PURCHASE_INVOICE,2009-08-05 16:48:40.952,2019-01-26 21:09:21.145,None,2019-01-26 21:09:19.636,2009-07-06 16:48:40.952,USD,INVOICE_READY,2009-07-06 16:52:52.901,8001,Company
11,AcctBigSupplier,2019-01-26 21:09:21.147,2019-01-26 21:09:19.636,PURCHASE_INVOICE,2009-08-10 12:24:31.850,2019-01-26 21:09:21.147,None,2019-01-26 21:09:19.636,2009-07-11 12:24:31.850,USD,INVOICE_PAID,2009-07-11 12:28:44.034,8002,Company
12,AcctBigSupplier,2019-01-26 21:09:21.148,2019-01-26 21:09:19.636,PURCHASE_INVOICE,2009-08-10 12:25:26.085,2019-01-26 21:09:21.148,None,2019-01-26 21:09:19.636,2009-07-11 12:25:26.085,USD,INVOICE_PAID,2009-07-11 12:28:44.034,8003,Company
13,DemoSupplier,2019-01-26 21:09:21.149,2019-01-26 21:09:19.636,PURCHASE_INVOICE,2009-08-10 12:26:29.758,2019-01-26 21:09:21.149,None,2019-01-26 21:09:19.636,2009-07-11 12:26:29.758,USD,INVOICE_PAID,2009-07-11 12:28:44.950,8004,Company
14,DemoSupplier,2019-01-26 21:09:21.392,2019-01-26 21:09:19.636,PURCHASE_INVOICE,2009-08-10 12:26:29.758,2019-01-26 21:09:21.392,Another invoice,2019-01-26 21:09:19.636,2009-07-11 12:26:29.758,USD,INVOICE_READY,NaT,8005,Company
15,AcctBigSupplier,2019-01-26 21:09:21.393,2019-01-26 21:09:19.636,PURCHASE_INVOICE,2009-08-10 12:25:26.085,2019-01-26 21:09:21.393,Another invoice,2019-01-26 21:09:19.636,2009-07-11 12:25:26.085,USD,INVOICE_READY,NaT,8006,Company
16,AcctBigSupplier,2019-01-26 21:09:21.395,2019-01-26 21:09:19.636,PURCHASE_INVOICE,2009-08-10 12:24:31.850,2019-01-26 21:09:21.395,Another invoice,2019-01-26 21:09:19.636,2009-07-11 12:24:31.850,USD,INVOICE_READY,NaT,8007,Company
17,DemoSupplier,2019-01-26 21:09:30.999,2019-01-26 21:09:22.215,PURCHASE_INVOICE,NaT,2019-01-26 21:09:30.999,Purchase Order Invoice,2019-01-26 21:09:22.215,2009-08-13 17:47:47.929,USD,INVOICE_READY,NaT,8008,Company
18,Company,2019-01-26 21:09:31.085,2019-01-26 21:09:22.215,SALES_INVOICE,NaT,2019-01-26 21:09:31.085,None,2019-01-26 21:09:22.215,2009-08-17 14:57:03.614,USD,INVOICE_PAID,2009-08-17 14:57:04.990,8009,DemoCustomer
19,Company,2019-01-26 21:09:31.137,2019-01-26 21:09:22.215,SALES_INVOICE,NaT,2019-01-26 21:09:31.137,None,2019-01-26 21:09:22.215,2009-09-17 14:57:03.614,USD,INVOICE_APPROVED,NaT,8010,DemoCustomer
20,Company,2019-01-26 21:09:21.382,2019-01-26 21:09:19.636,SALES_INVOICE,2009-08-07 11:54:00.765,2019-01-26 21:09:21.382,None,2019-01-26 21:09:19.636,2009-07-08 11:54:00.765,USD,INVOICE_PAID,2009-07-08 11:54:03.246,8100,admin
21,Company,2019-02-12 19:23:59.354,2019-02-12 19:23:59.351,SALES_INVOICE,2006-05-25 12:46:27.122,2019-02-12 19:23:59.354,This is the first invoice number to AcctBuyer,2019-02-12 19:23:59.351,2006-04-25 12:46:27.122,USD,INVOICE_SENT,NaT,appltest10000,DemoCustomer
22,Company,2019-01-26 21:09:21.111,2019-01-26 21:09:19.636,SALES_INVOICE,2006-05-25 12:46:27.122,2019-01-26 21:09:21.111,This is the first invoice number to AcctBuyer,2019-01-26 21:09:19.636,2006-04-25 12:46:27.122,USD,INVOICE_IN_PROCESS,NaT,demo10000,AcctBuyer
23,AcctBigSupplier,2019-01-26 21:09:21.115,2019-01-26 21:09:19.636,PURCHASE_INVOICE,2006-05-25 12:50:50.655,2019-01-26 21:09:21.115,Another invoice,2019-01-26 21:09:19.636,2006-04-25 12:50:50.655,USD,INVOICE_IN_PROCESS,NaT,demo10001,Company
24,Company,2019-01-26 21:09:21.118,2019-01-26 21:09:19.636,SALES_INVOICE,2006-05-25 12:54:07.011,2019-01-26 21:09:21.118,Another sales invoice,2019-01-26 21:09:19.636,2006-04-25 12:54:07.011,USD,INVOICE_SENT,NaT,demo10002,AcctBuyer
25,Company,2019-01-26 21:09:21.126,2019-01-26 21:09:19.636,SALES_INVOICE,2006-05-25 12:46:27.122,2019-01-26 21:09:21.126,This is the first invoice number to Eurocustom...,2019-01-26 21:09:19.636,2006-04-25 12:46:27.122,EUR,INVOICE_APPROVED,NaT,demo11000,EuroCustomer
26,Company,2019-01-26 21:09:21.130,2019-01-26 21:09:19.636,SALES_INVOICE,2006-05-25 12:46:27.122,2019-01-26 21:09:21.130,This is the first invoice number to Eurocustom...,2019-01-26 21:09:19.636,2006-04-25 12:46:27.122,EUR,INVOICE_APPROVED,NaT,demo11001,EuroCustomer
27,Company,2019-01-26 21:09:21.137,2019-01-26 21:09:19.636,SALES_INVOICE,2010-05-25 12:46:27.122,2019-01-26 21:09:21.137,This is an invoice to DemoCustomer,2019-01-26 21:09:19.636,2006-04-25 12:46:27.122,USD,INVOICE_APPROVED,NaT,demo1200,DemoCustCompany

In [16]:
ok,r=s().createPaymentApplication(invoiceId='appltest10000',
    paymentId='appltest10000')
print(ok,r)

True {'paymentTypeId': 'CUSTOMER_PAYMENT', 'paymentApplicationId': '10008', 'responseMessage': 'success', 'amountApplied': Decimal('20.00')}

In [18]:
amountApplied=r['amountApplied']
paymentApplicationId=r['paymentApplicationId']
paymentApplication=e().refPaymentApplication(paymentApplicationId)
format(paymentApplication)

+----------------------+-------------------------+
| name                 | value                   |
|----------------------+-------------------------|
| lastUpdatedStamp     | 2019-02-13 00:46:54.11  |
| toPaymentId          |                         |
| amountApplied        | 20.00                   |
| createdTxStamp       | 2019-02-13 00:46:54.082 |
| createdStamp         | 2019-02-13 00:46:54.11  |
| overrideGlAccountId  |                         |
| lastUpdatedTxStamp   | 2019-02-13 00:46:54.082 |
| invoiceItemSeqId     |                         |
| billingAccountId     |                         |
| paymentApplicationId | 10008                   |
| paymentId            | appltest10000           |
| taxAuthGeoId         |                         |
| invoiceId            | appltest10000           |
+----------------------+-------------------------+

In [19]:
payment=e().refPayment('appltest10000')
format(payment)

+--------------------------+-------------------------+
| name                     | value                   |
|--------------------------+-------------------------|
| roleTypeIdTo             |                         |
| finAccountTransId        |                         |
| partyIdFrom              | DemoCustomer            |
| lastUpdatedStamp         | 2019-02-12 23:17:57.536 |
| amount                   | 20.00                   |
| paymentPreferenceId      |                         |
| comments                 |                         |
| createdTxStamp           | 2019-02-12 19:23:59.351 |
| actualCurrencyAmount     |                         |
| createdStamp             | 2019-02-12 19:23:59.379 |
| overrideGlAccountId      |                         |
| lastUpdatedTxStamp       | 2019-02-12 23:17:57.53  |
| paymentMethodTypeId      | EFT_ACCOUNT             |
| actualCurrencyUomId      |                         |
| paymentTypeId            | CUSTOMER_PAYMENT        |
| currencyUomId            | USD                     |
| statusId                 | PMNT_NOT_PAID           |
| paymentId                | appltest10000           |
| paymentMethodId          |                         |
| paymentGatewayResponseId |                         |
| paymentRefNum            |                         |
| partyIdTo                | Company                 |
| effectiveDate            | 2006-04-25 12:56:54.292 |
+--------------------------+-------------------------+

In [20]:
notAppliedPayment=oc.j.PaymentWorker.getPaymentNotApplied(oc.delegator, 'appltest10000')
print(notAppliedPayment)

0.00

In [21]:
oc.import_package('org.apache.ofbiz.accounting.invoice.InvoiceWorker')
invoiceId='appltest10000'
notAppliedInvoice=oc.j.InvoiceWorker.getInvoiceNotApplied(oc.delegator, invoiceId)
print(notAppliedInvoice)

0.00

In [25]:
# <remove-value value-field="paymentApplication"/>
# paymentApplication.remove()
# oc.delegator.removeValue(paymentApplication)
oc.delegator.removeByPrimaryKey(paymentApplication.getPrimaryKey())

1