In [1]:
from sagas.ofbiz.services import OfService as s, oc, track
ok, r=track(lambda a: s().testScv(defaultValue=5.5, message="hello world"))
print(ok, r)

✔ testScv default 21 2020-04-24 17:46:29.103 ➷ 16 ms
True {'responseMessage': 'success', 'resp': 'service done'}

In [2]:
from sagas.ofbiz.services import OfService as s, oc, track
import sagas.ofbiz.entities as ee
from sagas.ofbiz.entities import OfEntity as e

# this is Deprecated service
ok,r=s().findParty(partyId='DemoCustomer',
    roleTypeId='CUSTOMER')
for el in r:
    print(el)
print(r['partyListSize'])
rs=r['partyList']
ee.record_list_df("Party", rs)

viewSize
lowIndex
partyTypes
paramList
viewIndex
currentRole
highIndex
responseMessage
partyList
roleTypes
partyListSize
0

Empty DataFrame
Columns: []
Index: []

In [3]:
ok,r=s().findParty(partyId='TestCustomer',
    roleTypeId='CUSTOMER')
ee.record_list_df("Party", r['partyList'])

Empty DataFrame
Columns: []
Index: []

In [8]:
# r['partyTypes']

In [4]:
ee.record_list_df("PartyType", r['partyTypes'])

,partyTypeId,lastUpdatedStamp,parentTypeId,hasTable,createdTxStamp,createdStamp,description,lastUpdatedTxStamp
0,AUTOMATED_AGENT,2019-03-04 12:33:10.225,None,N,2019-03-04 12:33:09.719,2019-03-04 12:33:10.225,Automated Agent,2019-03-04 12:33:09.719
1,CORPORATION,2019-03-04 12:33:10.234,LEGAL_ORGANIZATION,N,2019-03-04 12:33:09.719,2019-03-04 12:33:10.234,Corporation,2019-03-04 12:33:09.719
2,FAMILY,2019-03-04 12:33:10.230,INFORMAL_GROUP,N,2019-03-04 12:33:09.719,2019-03-04 12:33:10.230,Family,2019-03-04 12:33:09.719
3,GOVERNMENT_AGENCY,2019-03-04 12:33:10.235,LEGAL_ORGANIZATION,N,2019-03-04 12:33:09.719,2019-03-04 12:33:10.235,Government Agency,2019-03-04 12:33:09.719
4,INFORMAL_GROUP,2019-03-04 12:33:10.228,PARTY_GROUP,N,2019-03-04 12:33:09.719,2019-03-04 12:33:10.228,Informal Group,2019-03-04 12:33:09.719
5,LEGAL_ORGANIZATION,2019-03-04 12:33:10.233,PARTY_GROUP,N,2019-03-04 12:33:09.719,2019-03-04 12:33:10.233,Legal Organization,2019-03-04 12:33:09.719
6,PARTY_GROUP,2019-03-04 12:33:10.227,None,Y,2019-03-04 12:33:09.719,2019-03-04 12:33:10.227,Party Group,2019-03-04 12:33:09.719
7,PERSON,2019-03-04 12:33:10.226,None,Y,2019-03-04 12:33:09.719,2019-03-04 12:33:10.226,Person,2019-03-04 12:33:09.719
8,TEAM,2019-03-04 12:33:10.231,INFORMAL_GROUP,N,2019-03-04 12:33:09.719,2019-03-04 12:33:10.231,Team,2019-03-04 12:33:09.719

In [6]:
import sagas.ofbiz.entities as ee
from sagas.ofbiz.entities import OfEntity as e

df=e('df').allPartyRoleDetailAndPartyDetail()
# df.info()
# df=df.dropna(axis=1,how='all') 
df

,partyTypeId,hasTable,preferredCurrencyUomId,partyId,createdByUserLogin,logoImageUrl,firstName,groupName,statusId,lastName,description,lastModifiedByUserLogin,roleTypeId,parentTypeId,createdDate,middleName,personalTitle
0,PARTY_GROUP,N,None,accountant_group,None,None,None,Accountant Group,PARTY_ENABLED,None,Organization,None,ORGANIZATION_ROLE,MAIN_ROLE,NaT,None,None
1,PARTY_GROUP,N,None,accountant_group,None,None,None,Accountant Group,PARTY_ENABLED,None,Not Applicable,None,_NA_,None,NaT,None,None
2,PARTY_GROUP,N,None,ACCOUNTING,admin,None,None,Accounting department,PARTY_ENABLED,None,Department,admin,DEPARTMENT,ORGANIZATION_UNIT,2004-03-27 09:37:40.989,None,None
3,PARTY_GROUP,Y,None,ACCOUNTING,admin,None,None,Accounting department,PARTY_ENABLED,None,Internal Organization,admin,INTERNAL_ORGANIZATIO,ORGANIZATION_ROLE,2004-03-27 09:37:40.989,None,None
4,PARTY_GROUP,N,None,ACCOUNTING,admin,None,None,Accounting department,PARTY_ENABLED,None,Not Applicable,admin,_NA_,None,2004-03-27 09:37:40.989,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,PARTY_GROUP,Y,None,we_div,None,None,None,Western Europe,PARTY_ENABLED,None,Internal Organization,None,INTERNAL_ORGANIZATIO,ORGANIZATION_ROLE,NaT,None,None
267,PARTY_GROUP,N,None,widget_div,None,None,None,Widget Business Unit,PARTY_ENABLED,None,Division,None,DIVISION,ORGANIZATION_UNIT,NaT,None,None
268,PARTY_GROUP,Y,None,widget_div,None,None,None,Widget Business Unit,PARTY_ENABLED,None,Internal Organization,None,INTERNAL_ORGANIZATIO,ORGANIZATION_ROLE,NaT,None,None
269,PERSON,N,None,_NA_,None,None,None,None,PARTY_ENABLED,None,Carrier,None,CARRIER,ORGANIZATION_ROLE,NaT,None,None
270,PERSON,N,None,_NA_,None,None,None,None,PARTY_ENABLED,None,Not Applicable,None,_NA_,None,NaT,None,None

In [5]:
e('df').queryPartyRoleDetailAndPartyDetail(partyId='DemoCustomer',
    roleTypeId='CUSTOMER')

,partyTypeId,hasTable,partyId,firstName,statusId,lastName,description,roleTypeId
0,PERSON,N,DemoCustomer,Demo,PARTY_ENABLED,Customer,Customer,CUSTOMER