In [16]:
from sagas.crmsfa.odoo_facade import odoo, login
login()
lang='fr_FR'

Product = odoo.env['product.product']
odoo.env.context['lang'] = lang
product_ids = Product.search([])
for p in Product.name_get(product_ids):
    print(p)

[38, '[CONS_25630] Vis']
[37, '[CONS_89957] Boulon']
[13, '[DESK0004] Customizable Desk (Aluminium, Noir)']
[52, '[DESK0005] Customizable Desk (Personnalisé, Blanc)']
[53, '[DESK0006] Customizable Desk (Personnalisé, Noir)']
[50, '[Deposit] Dépôt']
[14, '[E-COM06] Corner Desk Right Sit']
[15, '[E-COM07] Large Cabinet']
[16, '[E-COM08] Storage Box']
[17, '[E-COM09] Large Desk']
[18, '[E-COM10] Pedal Bin']
[19, '[E-COM11] Cabinet with Doors']
[20, '[E-COM12] Conference Chair (Steel)']
[21, '[E-COM13] Conference Chair (Aluminium)']
[56, "[EVENT_REG] Inscription à l'évènement"]
[49, "[EXP_AF] Billet d'avion"]
[48, '[EXP_CT] Déplacement en voiture']
[47, '[EXP_GEN] Frais']
[2, '[EXP_HA] Hôtel']
[1, '[EXP_REST] Restaurant Expenses']
[10, '[FURN_0096] Customizable Desk (Steel, Blanc)']
[11, '[FURN_0097] Customizable Desk (Steel, Noir)']
[12, '[FURN_0098] Customizable Desk (Aluminium, Blanc)']
[22, '[FURN_0269] Office Chair Black']
[27, '[FURN_0789] Individual Workplace']
[23, '[FURN_1118] Corner Desk Black']
[45, '[FURN_2100] Drawer Black']
[36, '[FURN_2333] Pied de table']
[33, '[FURN_5555] Boîtier pour Cables']
[46, '[FURN_5623] Cassetto nero']
[28, '[FURN_6666] Acoustic Bloc Screens']
[31, '[FURN_6741] Large Meeting Table']
[42, '[FURN_7023] Wood Panel']
[39, '[FURN_7111] Ply Layer']
[5, '[FURN_7777] Office Chair']
[8, '[FURN_7800] Desk Combination']
[44, '[FURN_78236] Table Kit']
[26, '[FURN_7888] Desk Stand with Screen']
[40, '[FURN_8111] Wear Layer']
[30, '[FURN_8220] Four Person Desk']
[35, '[FURN_8522] Table Top']
[43, '[FURN_8621] Plastic Laminate']
[29, '[FURN_8855] Drawer']
[6, '[FURN_8888] Office Lamp']
[24, '[FURN_8900] Drawer Black']
[32, '[FURN_8999] Three-Seat Sofa']
[25, '[FURN_9001] Flipover']
[41, '[FURN_9111] Ply Veneer']
[34, '[FURN_9666] Table (MTO)']
[7, '[FURN_9999] Office Design Software']
[54, '[SERV_125889] Garantie (1 an)']
[51, 'Chair floor protection']
[55, 'Garantie (2 ans)']
[4, 'Virtual Home Staging']
[3, 'Virtual Interior Design']

In [6]:
def record_names(model_name):
    Model = odoo.env[model_name]
    model_ids = Model.search([])
    print("total", len(model_ids))
    # for rec in Model.browse(model_ids):
    for p in Model.name_get(model_ids):
        print(p)

# record_names('product.product')
record_names('res.lang')

total 5
[10, 'Chinese (Simplified) / 简体中文']
[1, 'English']
[27, 'French / Français']
[39, 'Japanese / 日本語']
[56, 'Russian / русский язык']

In [15]:
import sagas.util.pandas_helper as ph
def records(model_name, fields_get=['name']):
    Model = odoo.env[model_name]
    model_ids = Model.search([])
    print("total", len(model_ids))
    rs=[]
    for el in Model.browse(model_ids):
        rec=[]
        for fld in fields_get:
            rec.append(getattr(el, fld))
        rs.append(rec)
    return rs

cols=['name', 'code']
rs=records('res.lang', cols)
ph.to_df(rs, cols)

total 5

                          name   code
0  Chinese (Simplified) / 简体中文  zh_CN
1                      English  en_US
2            French / Français  fr_FR
3               Japanese / 日本語  ja_JP
4       Russian / русский язык  ru_RU

In [29]:
from sagas import to_df

def list_fields(model='res.lang', lang="zh_CN", get_view=False):
    # see data ref: stack/sagas/dataset/partner_obj.json
    odoo.env.context['lang'] = lang
    partner_obj = odoo.env[model]
    if get_view:
        obj = partner_obj.fields_view_get()
    else:
        obj = partner_obj.fields_get()
    # text = json.dumps(obj, indent=4, ensure_ascii=False)
    rs=[]
    for k,v in obj.items():
        rel=''
        if 'relation' in v:
            rel=v['relation']

        rs.append((k, v['type'], v['string'], rel))
    return to_df(rs, ['name', 'type', 'title', 'relation'])

list_fields(model='res.lang', lang="zh_CN", get_view=False)

             name       type      title   relation
0            name       char         名称
1            code       char       地区代码
2        iso_code       char      ISO代码
3    translatable    boolean        可翻译
4          active    boolean         有效
5       direction  selection         方向
6     date_format       char       日期格式
7     time_format       char       时间格式
8      week_start  selection  一个星期的第一天是
9        grouping       char      分割符格式
10  decimal_point       char      小数分割符
11  thousands_sep       char      千位分隔符
12             id    integer         ID
13   display_name       char       显示名称
14     create_uid   many2one        创建人  res.users
15    create_date   datetime       创建时间
16      write_uid   many2one      最后更新者  res.users
17     write_date   datetime     最后更新时间
18  __last_update   datetime      最后修改日

In [31]:
list_fields(model='res.lang', lang="ru_RU", get_view=False)

             name       type                   title   relation
0            name       char                Название
1            code       char         Код Локализации
2        iso_code       char                 ISO Код
3    translatable    boolean             Переводимый
4          active    boolean                 Активно
5       direction  selection             Направление
6     date_format       char             Формат даты
7     time_format       char          Формат времени
8      week_start  selection       First Day of Week
9        grouping       char      Формат разделителя
10  decimal_point       char  Десятичный разделитель
11  thousands_sep       char       Разделитель тысяч
12             id    integer                   Номер
13   display_name       char        Отображаемое Имя
14     create_uid   many2one                 Создано  res.users
15    create_date   datetime                  Создан
16      write_uid   many2one   Последний раз обновил  res.users
17     write_date   datetime    Последнее обновление
18  __last_update   datetime     Последнее изменение