## 时间序列
pandas具有简单，强大和高效的功能，用于在频率转换期间执行重采样操作（例如，将数据转换为5分钟数据）。 这在金融应用中非常常见，但不限于此。 请参阅时间序列部分：http://pandas.pydata.org/pandas-docs/version/0.20/timeseries.html#timeseries

In [2]:
import pandas as pd
rng = pd.date_range('1/1/2012', periods=100, freq='S')
rng
# 首先创建了一个100秒时间戳的系列，s为second的意思。
# 频率：字符串或pandas偏移对象，可选 一个pandas日期偏移字符串或相应的对象

DatetimeIndex(['2012-01-01 00:00:00', '2012-01-01 00:00:01',
               '2012-01-01 00:00:02', '2012-01-01 00:00:03',
               '2012-01-01 00:00:04', '2012-01-01 00:00:05',
               '2012-01-01 00:00:06', '2012-01-01 00:00:07',
               '2012-01-01 00:00:08', '2012-01-01 00:00:09',
               '2012-01-01 00:00:10', '2012-01-01 00:00:11',
               '2012-01-01 00:00:12', '2012-01-01 00:00:13',
               '2012-01-01 00:00:14', '2012-01-01 00:00:15',
               '2012-01-01 00:00:16', '2012-01-01 00:00:17',
               '2012-01-01 00:00:18', '2012-01-01 00:00:19',
               '2012-01-01 00:00:20', '2012-01-01 00:00:21',
               '2012-01-01 00:00:22', '2012-01-01 00:00:23',
               '2012-01-01 00:00:24', '2012-01-01 00:00:25',
               '2012-01-01 00:00:26', '2012-01-01 00:00:27',
               '2012-01-01 00:00:28', '2012-01-01 00:00:29',
               '2012-01-01 00:00:30', '2012-01-01 00:00:31',
               '2012-01-01 00:00:32', '2012-01-01 00:00:33',
               '2012-01-01 00:00:34', '2012-01-01 00:00:35',
               '2012-01-01 00:00:36', '2012-01-01 00:00:37',
               '2012-01-01 00:00:38', '2012-01-01 00:00:39',
               '2012-01-01 00:00:40', '2012-01-01 00:00:41',
               '2012-01-01 00:00:42', '2012-01-01 00:00:43',
               '2012-01-01 00:00:44', '2012-01-01 00:00:45',
               '2012-01-01 00:00:46', '2012-01-01 00:00:47',
               '2012-01-01 00:00:48', '2012-01-01 00:00:49',
               '2012-01-01 00:00:50', '2012-01-01 00:00:51',
               '2012-01-01 00:00:52', '2012-01-01 00:00:53',
               '2012-01-01 00:00:54', '2012-01-01 00:00:55',
               '2012-01-01 00:00:56', '2012-01-01 00:00:57',
               '2012-01-01 00:00:58', '2012-01-01 00:00:59',
               '2012-01-01 00:01:00', '2012-01-01 00:01:01',
               '2012-01-01 00:01:02', '2012-01-01 00:01:03',
               '2012-01-01 00:01:04', '2012-01-01 00:01:05',
               '2012-01-01 00:01:06', '2012-01-01 00:01:07',
               '2012-01-01 00:01:08', '2012-01-01 00:01:09',
               '2012-01-01 00:01:10', '2012-01-01 00:01:11',
               '2012-01-01 00:01:12', '2012-01-01 00:01:13',
               '2012-01-01 00:01:14', '2012-01-01 00:01:15',
               '2012-01-01 00:01:16', '2012-01-01 00:01:17',
               '2012-01-01 00:01:18', '2012-01-01 00:01:19',
               '2012-01-01 00:01:20', '2012-01-01 00:01:21',
               '2012-01-01 00:01:22', '2012-01-01 00:01:23',
               '2012-01-01 00:01:24', '2012-01-01 00:01:25',
               '2012-01-01 00:01:26', '2012-01-01 00:01:27',
               '2012-01-01 00:01:28', '2012-01-01 00:01:29',
               '2012-01-01 00:01:30', '2012-01-01 00:01:31',
               '2012-01-01 00:01:32', '2012-01-01 00:01:33',
               '2012-01-01 00:01:34', '2012-01-01 00:01:35',
               '2012-01-01 00:01:36', '2012-01-01 00:01:37',
               '2012-01-01 00:01:38', '2012-01-01 00:01:39'],
              dtype='datetime64[ns]', freq='S')

In [3]:
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)
ts

# 将刚产生的时间序列rng作为索引index，随机产生0-500之间的整数作为值。

2012-01-01 00:00:00    240
2012-01-01 00:00:01    408
2012-01-01 00:00:02    116
2012-01-01 00:00:03    106
2012-01-01 00:00:04    329
2012-01-01 00:00:05    139
2012-01-01 00:00:06    465
2012-01-01 00:00:07    412
2012-01-01 00:00:08     85
2012-01-01 00:00:09     76
2012-01-01 00:00:10     70
2012-01-01 00:00:11    295
2012-01-01 00:00:12    221
2012-01-01 00:00:13    424
2012-01-01 00:00:14     54
2012-01-01 00:00:15    241
2012-01-01 00:00:16      9
2012-01-01 00:00:17    347
2012-01-01 00:00:18    283
2012-01-01 00:00:19     95
2012-01-01 00:00:20     55
2012-01-01 00:00:21    340
2012-01-01 00:00:22    415
2012-01-01 00:00:23    205
2012-01-01 00:00:24    373
2012-01-01 00:00:25     51
2012-01-01 00:00:26    402
2012-01-01 00:00:27    443
2012-01-01 00:00:28     32
2012-01-01 00:00:29    212
                      ...
2012-01-01 00:01:10     78
2012-01-01 00:01:11    266
2012-01-01 00:01:12    415
2012-01-01 00:01:13    350
2012-01-01 00:01:14    290
2012-01-01 00:01:15    400
2012-01-01 00:01:16     88
2012-01-01 00:01:17    148
2012-01-01 00:01:18    342
2012-01-01 00:01:19    148
2012-01-01 00:01:20    455
2012-01-01 00:01:21     92
2012-01-01 00:01:22    475
2012-01-01 00:01:23    349
2012-01-01 00:01:24    174
2012-01-01 00:01:25    261
2012-01-01 00:01:26    219
2012-01-01 00:01:27     28
2012-01-01 00:01:28    219
2012-01-01 00:01:29    103
2012-01-01 00:01:30     62
2012-01-01 00:01:31    309
2012-01-01 00:01:32    470
2012-01-01 00:01:33     83
2012-01-01 00:01:34      9
2012-01-01 00:01:35     83
2012-01-01 00:01:36    498
2012-01-01 00:01:37    325
2012-01-01 00:01:38    305
2012-01-01 00:01:39    370
Freq: S, Length: 100, dtype: int64

In [4]:
# 将该系列缩小为5分钟,就是五分钟采样一次，并对其值进行求和：
ts.resample('5Min').sum()

2012-01-01    25869
Freq: 5T, dtype: int64

In [6]:
rng = pd.date_range('3/6/2012 00:00', periods=5, freq='D')
rng
# 注：产生5个数的时间序列，偏移量为D：Day，日期

DatetimeIndex(['2012-03-06', '2012-03-07', '2012-03-08', '2012-03-09',
               '2012-03-10'],
              dtype='datetime64[ns]', freq='D')

In [7]:
ts = pd.Series(np.random.randn(len(rng)), rng)
ts
# 注：将产生的日期作为索引，产生日起数量（5个）的标准正态分布的数值

2012-03-06   -0.898854
2012-03-07    0.175655
2012-03-08    0.000501
2012-03-09   -0.681926
2012-03-10   -2.012480
Freq: D, dtype: float64

In [8]:
# 本地化时区表示：
ts_utc = ts.tz_localize('UTC')
ts_utc

2012-03-06 00:00:00+00:00   -0.898854
2012-03-07 00:00:00+00:00    0.175655
2012-03-08 00:00:00+00:00    0.000501
2012-03-09 00:00:00+00:00   -0.681926
2012-03-10 00:00:00+00:00   -2.012480
Freq: D, dtype: float64

In [9]:
# 转换成其他时区：
ts_utc.tz_convert('US/Eastern')

2012-03-05 19:00:00-05:00   -0.898854
2012-03-06 19:00:00-05:00    0.175655
2012-03-07 19:00:00-05:00    0.000501
2012-03-08 19:00:00-05:00   -0.681926
2012-03-09 19:00:00-05:00   -2.012480
Freq: D, dtype: float64

In [10]:
# 在时间跨度表示之间转换：
rng = pd.date_range('1/1/2012', periods=5, freq='M')
ts = pd.Series(np.random.randn(len(rng)), index=rng)
ts

2012-01-31   -1.180201
2012-02-29   -0.093215
2012-03-31   -0.832634
2012-04-30   -1.553774
2012-05-31    0.407096
Freq: M, dtype: float64

In [11]:
ps = ts.to_period()
ps
# 注：将时间日期索引转化为时间阶段索引（这里是用月份表示）

2012-01   -1.180201
2012-02   -0.093215
2012-03   -0.832634
2012-04   -1.553774
2012-05    0.407096
Freq: M, dtype: float64

In [12]:
ps.to_timestamp()
# 注：用月份的初始日期表示

2012-01-01   -1.180201
2012-02-01   -0.093215
2012-03-01   -0.832634
2012-04-01   -1.553774
2012-05-01    0.407096
Freq: MS, dtype: float64