In [2]:
# Shipment
from sagas.ofbiz.services import OfService as s, oc, track
from sagas.ofbiz.entities import OfEntity as e

e('meta').Shipment

                          name primary             type       field type
0                   shipmentId       *               id               id
1               shipmentTypeId                       id               id
2                     statusId                       id               id
3               primaryOrderId                       id               id
4              primaryReturnId                       id               id
5        primaryShipGroupSeqId                       id               id
6                picklistBinId                       id               id
7           estimatedReadyDate                date-time        date-time
8            estimatedShipDate                date-time        date-time
9       estimatedShipWorkEffId                       id               id
10        estimatedArrivalDate                date-time        date-time
11   estimatedArrivalWorkEffId                       id               id
12            latestCancelDate                date-time        date-time
13           estimatedShipCost          currency-amount  currency-amount
14               currencyUomId                       id               id
15        handlingInstructions             long-varchar     long-varchar
16            originFacilityId                       id               id
17       destinationFacilityId                       id               id
18         originContactMechId                       id               id
19       originTelecomNumberId                       id               id
20    destinationContactMechId                       id               id
21  destinationTelecomNumberId                       id               id
22                   partyIdTo                       id               id
23                 partyIdFrom                       id               id
24    additionalShippingCharge          currency-amount  currency-amount
25     addtlShippingChargeDesc             long-varchar     long-varchar
26                 createdDate                date-time        date-time
27          createdByUserLogin                 id-vlong         id-vlong
28            lastModifiedDate                date-time        date-time
29     lastModifiedByUserLogin                 id-vlong         id-vlong
30            lastUpdatedStamp                date-time        date-time
31          lastUpdatedTxStamp                date-time        date-time
32                createdStamp                date-time        date-time
33              createdTxStamp                date-time        date-time

In [4]:
e('meta').Payment

                        name primary             type       field type
0                  paymentId       *               id               id
1              paymentTypeId                       id               id
2        paymentMethodTypeId                       id               id
3            paymentMethodId                       id               id
4   paymentGatewayResponseId                       id               id
5        paymentPreferenceId                       id               id
6                partyIdFrom                       id               id
7                  partyIdTo                       id               id
8               roleTypeIdTo                       id               id
9                   statusId                       id               id
10             effectiveDate                date-time        date-time
11             paymentRefNum            short-varchar    short-varchar
12                    amount          currency-amount  currency-amount
13             currencyUomId                       id               id
14                  comments                  comment          comment
15         finAccountTransId                       id               id
16       overrideGlAccountId                       id               id
17      actualCurrencyAmount          currency-amount  currency-amount
18       actualCurrencyUomId                       id               id
19          lastUpdatedStamp                date-time        date-time
20        lastUpdatedTxStamp                date-time        date-time
21              createdStamp                date-time        date-time
22            createdTxStamp                date-time        date-time