In [1]:
import sagas.ofbiz.entities as ee
import json

ent=ee.entity('Product')
val=ent.record('GZ-2002')
val_json=ent.to_json(val,True)
print(json.dumps(val_json, indent=2, ensure_ascii=False))

{
  "createdStamp": "2019-03-03T22:33:37.435000",
  "productName": "Square Gizmo",
  "createdByUserLogin": "admin",
  "productId": "GZ-2002",
  "smallImageUrl": "/images/products/GZ-2002/small.png",
  "taxable": "Y",
  "primaryProductCategoryId": "101",
  "createdTxStamp": "2019-03-03T22:33:34.232000",
  "lastUpdatedTxStamp": "2019-03-03T22:33:54.833000",
  "isVirtual": "N",
  "autoCreateKeywords": "Y",
  "description": "A square gizmo",
  "chargeShipping": "Y",
  "internalName": "Square Gizmo",
  "lastModifiedByUserLogin": "admin",
  "lastUpdatedStamp": "2019-03-03T22:33:54.941000",
  "lastModifiedDate": "2001-05-13T12:00:00",
  "productTypeId": "FINISHED_GOOD",
  "createdDate": "2001-05-13T12:00:00",
  "isVariant": "N",
  "largeImageUrl": "/images/products/GZ-2002/large.png"
}

In [6]:
oc=ee.oc
def to_json(val, filter=False):
    import sagas.graph.value_filter as vf
    ret = oc.j.ValueHelper.entityToJson(val, oc.jmap())
    jval = json.loads(ret)
    model = oc.delegator.getModelEntity(val.getEntityName())
    if filter:
        return vf.filter_json_val(model, jval)
    return jval

# ProductCategory
relname="PrimaryProductCategory"
cat=val.getRelatedOne(relname, False)
relation = val.getModelEntity().getRelation(relname)
reltype=relation.getType()
if reltype=='one' or reltype=='one-nofk':
    print('relation type %s is one'%relname)
rel_json=to_json(cat, True)

print(json.dumps(rel_json, indent=2, ensure_ascii=False))

relation type PrimaryProductCategory is one
{
  "longDescription": "long description of Small Gizmos",
  "lastUpdatedStamp": "2019-03-03T22:33:34.863000",
  "productCategoryTypeId": "CATALOG_CATEGORY",
  "createdTxStamp": "2019-03-03T22:33:34.232000",
  "createdStamp": "2019-03-03T22:33:34.863000",
  "lastUpdatedTxStamp": "2019-03-03T22:33:34.232000",
  "productCategoryId": "101",
  "primaryParentCategoryId": "100"
}

In [7]:
from sagas.ofbiz.entities import OfEntity as e
# e('meta').Person
e('relations').Survey

,entity name,mapping,relation,type,relation type
0,DataResource,surveyId►surveyId,DataResource,many,many
1,ProductStoreFinActSetting,surveyId►purchaseSurveyId,ProductStoreFinActSetting,many,many
2,ProductStoreSurveyAppl,surveyId►surveyId,ProductStoreSurveyAppl,many,many
3,SurveyMultiResp,surveyId►surveyId,SurveyMultiResp,many,many
4,SurveyPage,surveyId►surveyId,SurveyPage,many,many
5,SurveyQuestionAppl,surveyId►surveyId,SurveyQuestionAppl,many,many
6,SurveyResponse,surveyId►surveyId,SurveyResponse,many,many
7,SurveyTrigger,surveyId►surveyId,SurveyTrigger,many,many
8,WorkEffortSurveyAppl,surveyId►surveyId,WorkEffortSurveyAppl,many,many

In [8]:
e('relations').Example

,entity name,mapping,relation,type,relation type
0,ExampleType,exampleTypeId►exampleTypeId,ExampleType,one,one
1,StatusItem,statusId►statusId,StatusItem,one,one
2,ExampleFeatureAppl,exampleId►exampleId,ExampleFeatureAppl,many,many
3,ExampleItem,exampleId►exampleId,ExampleItem,many,many
4,ExampleStatus,exampleId►exampleId,ExampleStatus,many,many

In [10]:
e('df').listExample()

,lastUpdatedStamp,exampleTypeId,exampleId,createdTxStamp,createdStamp,lastUpdatedTxStamp,statusId,exampleName
0,2019-03-03 22:34:00.162,CONTRIVED,EX01,2019-03-03 22:34:00.092,2019-03-03 22:34:00.162,2019-03-03 22:34:00.092,EXST_IN_DESIGN,Example 1
1,2019-03-03 22:34:00.163,CONTRIVED,EX02,2019-03-03 22:34:00.092,2019-03-03 22:34:00.163,2019-03-03 22:34:00.092,EXST_IN_DESIGN,Example 2
2,2019-03-03 22:34:00.164,CONTRIVED,EX03,2019-03-03 22:34:00.092,2019-03-03 22:34:00.164,2019-03-03 22:34:00.092,EXST_IN_DESIGN,Example 3
3,2019-03-03 22:34:00.166,REAL_WORLD,EX04,2019-03-03 22:34:00.092,2019-03-03 22:34:00.166,2019-03-03 22:34:00.092,EXST_IN_DESIGN,Example 4
4,2019-03-03 22:34:00.167,REAL_WORLD,EX05,2019-03-03 22:34:00.092,2019-03-03 22:34:00.167,2019-03-03 22:34:00.092,EXST_IN_DESIGN,Example 5
5,2019-03-03 22:34:00.172,MADE_UP,EX06,2019-03-03 22:34:00.092,2019-03-03 22:34:00.172,2019-03-03 22:34:00.092,EXST_IN_DESIGN,Example 6
6,2019-03-03 22:34:00.173,MADE_UP,EX07,2019-03-03 22:34:00.092,2019-03-03 22:34:00.173,2019-03-03 22:34:00.092,EXST_IN_DESIGN,Example 7
7,2019-03-03 22:34:00.175,MADE_UP,EX08,2019-03-03 22:34:00.092,2019-03-03 22:34:00.175,2019-03-03 22:34:00.092,EXST_IN_DESIGN,Example 8
8,2019-03-03 22:34:00.176,MADE_UP,EX09,2019-03-03 22:34:00.092,2019-03-03 22:34:00.176,2019-03-03 22:34:00.092,EXST_IN_DESIGN,Example 9
9,2019-03-03 22:34:00.190,MADE_UP,EX10,2019-03-03 22:34:00.092,2019-03-03 22:34:00.178,2019-03-03 22:34:00.092,EXST_IN_DESIGN,Example 10 after update

In [4]:
from sagas.ofbiz.entities import OfEntity as e
print(e().countSurvey(), e().countPerson(), 
      e().countExampleItem(),
      e().countExample())

14 53 5 14

In [6]:
import sagas.graph.dgraph_helper as helper
import pydgraph
client = helper.create_client()
helper.run_q(client, '''schema {}
''')

{
  "schema": [
    {
      "predicate": "_predicate_",
      "type": "string",
      "list": true
    },
    {
      "predicate": "amount",
      "type": "float"
    },
    {
      "predicate": "amountUomId",
      "type": "string"
    },
    {
      "predicate": "changeByUserLoginId",
      "type": "string"
    },
    {
      "predicate": "createdStamp",
      "type": "datetime"
    },
    {
      "predicate": "createdTxStamp",
      "type": "datetime"
    },
    {
      "predicate": "description",
      "type": "string"
    },
    {
      "predicate": "dgraph.group.acl",
      "type": "string"
    },
    {
      "predicate": "dgraph.password",
      "type": "password"
    },
    {
      "predicate": "dgraph.user.group",
      "type": "uid",
      "reverse": true
    },
    {
      "predicate": "dgraph.xid",
      "type": "string",
      "index": true,
      "tokenizer": [
        "exact"
      ]
    },
    {
      "predicate": "exampleFeatureApplTypeId",
      "type": "string"
    },
    {
      "predicate": "exampleFeatureId",
      "type": "string",
      "index": true,
      "tokenizer": [
        "exact"
      ]
    },
    {
      "predicate": "exampleId",
      "type": "string",
      "index": true,
      "tokenizer": [
        "exact"
      ]
    },
    {
      "predicate": "exampleItemSeqId",
      "type": "string",
      "index": true,
      "tokenizer": [
        "exact"
      ]
    },
    {
      "predicate": "exampleTypeId",
      "type": "string",
      "index": true,
      "tokenizer": [
        "exact"
      ]
    },
    {
      "predicate": "fromDate",
      "type": "datetime"
    },
    {
      "predicate": "lastUpdatedStamp",
      "type": "datetime"
    },
    {
      "predicate": "lastUpdatedTxStamp",
      "type": "datetime"
    },
    {
      "predicate": "mo_field",
      "type": "uid"
    },
    {
      "predicate": "mo_form_uri",
      "type": "string"
    },
    {
      "predicate": "mo_last_modified",
      "type": "datetime"
    },
    {
      "predicate": "mo_mode",
      "type": "string"
    },
    {
      "predicate": "mo_name",
      "type": "string",
      "index": true,
      "tokenizer": [
        "exact"
      ]
    },
    {
      "predicate": "mo_primary",
      "type": "bool"
    },
    {
      "predicate": "mo_primary_keys",
      "type": "string",
      "index": true,
      "tokenizer": [
        "term"
      ],
      "list": true
    },
    {
      "predicate": "mo_relation",
      "type": "uid",
      "reverse": true
    },
    {
      "predicate": "mo_service",
      "type": "string"
    },
    {
      "predicate": "mo_table",
      "type": "string"
    },
    {
      "predicate": "mo_total",
      "type": "int"
    },
    {
      "predicate": "mo_type",
      "type": "string"
    },
    {
      "predicate": "parentTypeId",
      "type": "string"
    },
    {
      "predicate": "sequenceId",
      "type": "string"
    },
    {
      "predicate": "sequenceNum",
      "type": "int"
    },
    {
      "predicate": "statusCode",
      "type": "string"
    },
    {
      "predicate": "statusDate",
      "type": "datetime"
    },
    {
      "predicate": "statusEndDate",
      "type": "datetime"
    },
    {
      "predicate": "statusId",
      "type": "string",
      "index": true,
      "tokenizer": [
        "exact"
      ]
    },
    {
      "predicate": "statusTypeId",
      "type": "string"
    },
    {
      "predicate": "thruDate",
      "type": "datetime"
    }
  ]
}

In [13]:
from sagas.ofbiz.entity_graph import EntityGraph
from sagas.graph.rss_hub import set_json
import json_utils

eg=EntityGraph()
eg.setup_schema_head('Example')
file='./data/ofbiz/rs_Example.json'
feed_json = json_utils.read_json_file(file)
_ = set_json(client, feed_json)

.. getting schema for entities: ExampleItem, ExampleFeatureAppl, StatusItem, ExampleType, ExampleStatus
deduce fields 0
total fields 19

mo_name: string @index(exact) .
mo_relation: uid @reverse .
mo_total: int .
mo_last_modified: datetime .
mo_table: string .
mo_service: string .
mo_form_uri: string .
mo_field: uid .
mo_type: string .
mo_mode: string .
mo_primary: bool .
mo_primary_keys: [string] @index(term) .
lastUpdatedStamp: datetime .
lastUpdatedTxStamp: datetime .
createdStamp: datetime .
createdTxStamp: datetime .
exampleId: string @index(exact) .
exampleItemSeqId: string @index(exact) .
description: string .
amount: float .
amountUomId: string .
exampleFeatureId: string @index(exact) .
fromDate: datetime .
thruDate: datetime .
exampleFeatureApplTypeId: string .
sequenceNum: int .
statusId: string @index(exact) .
statusTypeId: string .
statusCode: string .
sequenceId: string .
exampleTypeId: string @index(exact) .
parentTypeId: string .
statusDate: datetime .
statusEndDate: datetime .
changeByUserLoginId: string .
done.

In [14]:
query = """{
  find_ex(func: eq(exampleId, "EX01")) {
    uid
    mo_type
    exampleId
    exampleName
    description
    createdStamp
  }
}
"""
rs=eg.gm.query(query)
print(json.dumps(rs, indent=True))

{
 "find_ex": [
  {
   "uid": "0x6d6c7",
   "mo_type": "ExampleItem",
   "exampleId": "EX01",
   "description": "EX1-001",
   "createdStamp": "2019-03-03T22:34:00.193Z"
  },
  {
   "uid": "0x6d6cb",
   "mo_type": "ExampleStatus",
   "exampleId": "EX01",
   "createdStamp": "2019-03-03T22:34:00.207Z"
  },
  {
   "uid": "0x6d6cc",
   "mo_type": "ExampleItem",
   "exampleId": "EX01",
   "description": "EX1-002",
   "createdStamp": "2019-03-03T22:34:00.195Z"
  },
  {
   "uid": "0x6d6d2",
   "mo_type": "ExampleStatus",
   "exampleId": "EX01",
   "createdStamp": "2019-03-03T22:34:00.205Z"
  },
  {
   "uid": "0x6d6d7",
   "mo_type": "Example",
   "exampleId": "EX01",
   "exampleName": "Example 1",
   "createdStamp": "2019-03-03T22:34:00.162Z"
  },
  {
   "uid": "0x6d6d8",
   "mo_type": "ExampleStatus",
   "exampleId": "EX01",
   "createdStamp": "2019-03-03T22:34:00.203Z"
  }
 ]
}

In [16]:
import pandas as pd
cols=['uid','mo_type','exampleId','exampleName','description','createdStamp']
query = """{
  find_ex(func: eq(exampleId, "EX01")) {
  %s
  }
}
"""%'\n'.join(cols)
rs=eg.gm.query(query)
find_ex=rs['find_ex']
df=pd.DataFrame(find_ex, columns=cols)
df

,uid,mo_type,exampleId,exampleName,description,createdStamp
0,0x6d6c7,ExampleItem,EX01,NaN,EX1-001,2019-03-03T22:34:00.193Z
1,0x6d6cb,ExampleStatus,EX01,NaN,NaN,2019-03-03T22:34:00.207Z
2,0x6d6cc,ExampleItem,EX01,NaN,EX1-002,2019-03-03T22:34:00.195Z
3,0x6d6d2,ExampleStatus,EX01,NaN,NaN,2019-03-03T22:34:00.205Z
4,0x6d6d7,Example,EX01,Example 1,NaN,2019-03-03T22:34:00.162Z
5,0x6d6d8,ExampleStatus,EX01,NaN,NaN,2019-03-03T22:34:00.203Z