In [13]:
from sagas.ofbiz.services import OfService, MetaService
from sagas.ofbiz.entities import MetaEntity
from tabulate import tabulate

def print_record(ent_name, id, show_null=True):
    table_header = ['name','value']
    table_data = []
    rec=MetaEntity(ent_name).record(id)
    for k,v in rec.items():
        if v is None and not show_null:
            pass
        else:
            table_data.append((k, v))
    print(tabulate(table_data, headers=table_header, tablefmt='psql'))   

print_record("InventoryItem", '9024', True)

+-------------------------+-------------------------+
| name                    | value                   |
|-------------------------+-------------------------|
| softIdentifier          |                         |
| createdStamp            | 2019-01-26 21:09:28.176 |
| binNumber               |                         |
| oldAvailableToPromise   |                         |
| quantityOnHandTotal     | 8.000000                |
| datetimeManufactured    |                         |
| expireDate              |                         |
| oldQuantityOnHand       |                         |
| partyId                 |                         |
| containerId             |                         |
| availableToPromiseTotal | 8.000000                |
| inventoryItemTypeId     | NON_SERIAL_INV_ITEM     |
| locationSeqId           |                         |
| lastUpdatedStamp        | 2019-02-03 00:48:34.827 |
| facilityId              | WebStoreWarehouse       |
| comments                |                         |
| serialNumber            |                         |
| productId               | GZ-1006-4               |
| createdTxStamp          | 2019-01-26 21:09:22.215 |
| lastUpdatedTxStamp      | 2019-02-03 00:48:34.68  |
| lotId                   |                         |
| uomId                   |                         |
| accountingQuantityTotal | 8.000000                |
| inventoryItemId         | 9024                    |
| ownerPartyId            | Company                 |
| activationValidThru     |                         |
| activationNumber        |                         |
| currencyUomId           | USD                     |
| statusId                |                         |
| unitCost                | 2.400000                |
| fixedAssetId            |                         |
| datetimeReceived        | 2008-08-01 08:00:00.0   |
+-------------------------+-------------------------+

In [14]:
print_record("InventoryItem", '9024', False)

+-------------------------+-------------------------+
| name                    | value                   |
|-------------------------+-------------------------|
| createdStamp            | 2019-01-26 21:09:28.176 |
| quantityOnHandTotal     | 8.000000                |
| availableToPromiseTotal | 8.000000                |
| inventoryItemTypeId     | NON_SERIAL_INV_ITEM     |
| lastUpdatedStamp        | 2019-02-03 00:48:34.827 |
| facilityId              | WebStoreWarehouse       |
| productId               | GZ-1006-4               |
| createdTxStamp          | 2019-01-26 21:09:22.215 |
| lastUpdatedTxStamp      | 2019-02-03 00:48:34.68  |
| accountingQuantityTotal | 8.000000                |
| inventoryItemId         | 9024                    |
| ownerPartyId            | Company                 |
| currencyUomId           | USD                     |
| unitCost                | 2.400000                |
| datetimeReceived        | 2008-08-01 08:00:00.0   |
+-------------------------+-------------------------+

In [2]:
product=MetaEntity("Product").record("GZ-2002")
ok, ret=OfService().calculateProductPrice(product=product)
print(ret['defaultPrice'], ret['listPrice'])

47.990 48.000

In [5]:
print(MetaEntity('ProductPrice').primary)
MetaEntity('ProductPrice').desc(False)

['productId', 'productPriceTypeId', 'productPricePurposeId', 'currencyUomId', 'productStoreGroupId', 'fromDate']
PRODUCT_PRICE Product Price None
+------------------------+------------------+-----------------------------+
| name                   | type             | string                      |
|------------------------+------------------+-----------------------------|
| taxInPrice             | indicator        | TAX_IN_PRICE                |
| termUomId              | id               | TERM_UOM_ID                 |
| priceWithTax           | currency-precise | PRICE_WITH_TAX              |
| productStoreGroupId    | id               | PRODUCT_STORE_GROUP_ID      |
| taxAuthPartyId         | id               | TAX_AUTH_PARTY_ID           |
| lastModifiedByUserLo.. | id-vlong         | LAST_MODIFIED_BY_USER_LOG.. |
| customPriceCalcServi.. | id               | CUSTOM_PRICE_CALC_SERVICE   |
| price                  | currency-precise | PRICE                       |
| taxAuthGeoId           | id               | TAX_AUTH_GEO_ID             |
| productPricePurposeI.. | id               | PRODUCT_PRICE_PURPOSE_ID    |
| createdByUserLogin     | id-vlong         | CREATED_BY_USER_LOGIN       |
| productId              | id               | PRODUCT_ID                  |
| lastModifiedDate       | date-time        | LAST_MODIFIED_DATE          |
| taxPercentage          | fixed-point      | TAX_PERCENTAGE              |
| thruDate               | date-time        | THRU_DATE                   |
| fromDate               | date-time        | FROM_DATE                   |
| currencyUomId          | id               | CURRENCY_UOM_ID             |
| createdDate            | date-time        | CREATED_DATE                |
| priceWithoutTax        | currency-precise | PRICE_WITHOUT_TAX           |
| taxAmount              | currency-precise | TAX_AMOUNT                  |
| productPriceTypeId     | id               | PRODUCT_PRICE_TYPE_ID       |
+------------------------+------------------+-----------------------------+
+---------------------+--------+-------------------------+
| name                | type   | string                  |
|---------------------+--------+-------------------------|
| Product             | one    | Product                 |
| ProductPriceType    | one    | ProductPriceType        |
| ProductPricePurpose | one    | ProductPricePurpose     |
| Uom                 | one    | CurrencyUom             |
| Uom                 | one    | TermUom                 |
| ProductStoreGroup   | one    | ProductStoreGroup       |
| CustomMethod        | one    | CustomMethod            |
| Party               | one    | TaxAuthorityParty       |
| Geo                 | one    | TaxAuthorityGeo         |
| UserLogin           | one    | CreatedByUserLogin      |
| UserLogin           | one    | LastModifiedByUserLogin |
| ProductPriceChange  | many   | ProductPriceChange      |
+---------------------+--------+-------------------------+

In [9]:
print(MetaEntity('Product').primary)
print(MetaEntity('ProductAssoc').primary)

['productId']
['productId', 'productIdTo', 'productAssocTypeId', 'fromDate']

In [12]:
ret=MetaEntity('ProductStore').record('Test_store')
print(ret)

None

In [15]:
for rec in MetaEntity('ProductStore').find_list():
    print(rec['productStoreId'])

9000
RentalStore

In [18]:
import os
print(os.getcwd())
data_folder=os.getcwd()+"/data/product"
OfService().entityImportDir(path=data_folder)

/Users/xiaofeiwu/jcloud/assets/langs/workspace/rasa/stack

(True,
 {'messages': ['Got 10 entities from ProductPriceTestData.xml', 'Got 26 entities from IssuanceTestData.xml', 'Got 11 entities from ProductTestData.xml', 'Pass 1 complete', '---------------------------------------', 'Succeeded: 3 of 3', 'Failed: 0 of 3', '---------------------------------------', 'Failed Files:']})

In [15]:
# MetaEntity('ProductStore').record('Test_store')
print_record('ProductStore', 'Test_store', False)

+--------------------+-------------------------+
| name               | value                   |
|--------------------+-------------------------|
| createdStamp       | 2019-02-03 01:40:00.644 |
| createdTxStamp     | 2019-02-03 01:40:00.584 |
| lastUpdatedTxStamp | 2019-02-03 01:40:00.584 |
| productStoreId     | Test_store              |
| lastUpdatedStamp   | 2019-02-03 01:40:00.644 |
+--------------------+-------------------------+

In [16]:
def entity_method(*args, **kwargs):
    print(args[0])
entity_method('id')

id

In [1]:
from sagas.ofbiz.services import OfService as s
from sagas.ofbiz.entities import OfEntity as e
import sagas.ofbiz.entities as ee

ok, result=s().calculateProductPrice(product=e().refProduct('GZ-2002'))
ee.format(result)

+---------------------+---------+
| name                | value   |
|---------------------+---------|
| defaultPrice        | 47.990  |
| currencyUsed        | USD     |
| price               | 47.990  |
| orderItemPriceInfos | []      |
| specialPromoPrice   |         |
| isSale              | False   |
| validPriceFound     | True    |
| averageCost         | 48.000  |
| competitivePrice    |         |
| listPrice           | 48.000  |
| basePrice           | 47.990  |
+---------------------+---------+

In [2]:
from sagas.ofbiz.services import OfService as s
from sagas.ofbiz.entities import OfEntity as e
import sagas.ofbiz.entities as ee

s('meta').calculateProductPrice

,description,entity name,mode,name,primary,type,parameter mode
0,,,IN,product,*,org.apache.ofbiz.entity.GenericValue,IN
1,,,IN,prodCatalogId,,String,IN
2,,,IN,webSiteId,,String,IN
3,,,IN,partyId,,String,IN
4,,,IN,productStoreId,,String,IN
5,,,IN,productStoreGroupId,,String,IN
6,,,IN,agreementId,,String,IN
7,,,IN,quantity,,BigDecimal,IN
8,,,IN,amount,,BigDecimal,IN
9,,,IN,currencyUomId,,String,IN
10,,,IN,currencyUomIdTo,,String,IN
11,,,IN,productPricePurposeId,,String,IN
12,,,IN,termUomId,,String,IN
13,,,IN,autoUserLogin,,org.apache.ofbiz.entity.GenericValue,IN
14,,,IN,checkIncludeVat,,String,IN
15,,,IN,findAllQuantityPrices,,String,IN
16,,,IN,surveyResponseId,,String,IN
17,,,IN,customAttributes,,Map,IN
18,,,OUT,basePrice,*,BigDecimal,OUT
19,,,OUT,price,*,BigDecimal,OUT
20,,,OUT,listPrice,,BigDecimal,OUT
21,,,OUT,defaultPrice,,BigDecimal,OUT
22,,,OUT,competitivePrice,,BigDecimal,OUT
23,,,OUT,averageCost,,BigDecimal,OUT
24,,,OUT,promoPrice,,BigDecimal,OUT
25,,,OUT,specialPromoPrice,,BigDecimal,OUT
26,,,OUT,isSale,*,Boolean,OUT
27,,,OUT,validPriceFound,*,Boolean,OUT
28,,,OUT,currencyUsed,*,String,OUT
29,,,OUT,orderItemPriceInfos,*,java.util.List,OUT
30,,,OUT,allQuantityPrices,,java.util.List,OUT
31,,,IN,optimizeForLargeRuleSet,,String,IN
32,None,None,OUT,responseMessage,,String,OUT
33,None,None,OUT,errorMessage,,String,OUT
34,None,None,OUT,errorMessageList,,java.util.List,OUT
35,None,None,OUT,successMessage,,String,OUT
36,None,None,OUT,successMessageList,,java.util.List,OUT
37,None,None,INOUT,userLogin,,org.apache.ofbiz.entity.GenericValue,INOUT
38,None,None,IN,login.username,,String,IN
39,None,None,IN,login.password,,String,IN
40,None,None,INOUT,locale,,java.util.Locale,INOUT
41,None,None,INOUT,timeZone,,java.util.TimeZone,INOUT
42,None,None,INOUT,visualTheme,,org.apache.ofbiz.widget.renderer.VisualTheme,INOUT

In [1]:
from sagas.ofbiz.entities import OfEntity as e
e('meta').Person

                        name primary            type      field type
0                    partyId       *              id              id
1                 salutation                    name            name
2                  firstName                    name            name
3                 middleName                    name            name
4                   lastName                    name            name
5              personalTitle                    name            name
6                     suffix                    name            name
7                   nickname                    name            name
8             firstNameLocal                    name            name
9            middleNameLocal                    name            name
10             lastNameLocal                    name            name
11                otherLocal                    name            name
12                  memberId                      id              id
13                    gender               indicator       indicator
14                 birthDate                    date            date
15              deceasedDate                    date            date
16                    height          floating-point  floating-point
17                    weight          floating-point  floating-point
18         mothersMaidenName            long-varchar    long-varchar
19             maritalStatus               indicator       indicator
20      socialSecurityNumber            long-varchar    long-varchar
21            passportNumber            long-varchar    long-varchar
22        passportExpireDate                    date            date
23  totalYearsWorkExperience          floating-point  floating-point
24                  comments                 comment         comment
25    employmentStatusEnumId                      id              id
26     residenceStatusEnumId                      id              id
27                occupation                    name            name
28         yearsWithEmployer                 numeric         numeric
29        monthsWithEmployer                 numeric         numeric
30          existingCustomer               indicator       indicator
31                    cardId                 id-long         id-long
32          lastUpdatedStamp               date-time       date-time
33        lastUpdatedTxStamp               date-time       date-time
34              createdStamp               date-time       date-time
35            createdTxStamp               date-time       date-time

In [2]:
e('relations').Person

                entity name                     relation  type relation type
0                     Party                        Party   one           one
1               Enumeration  EmploymentStatusEnumeration   one           one
2               Enumeration   ResidenceStatusEnumeration   one           one
3          PartyContactMech             PartyContactMech  many          many
4   PartyContactMechPurpose      PartyContactMechPurpose  many          many
5            PersonTraining       ApproverPersonTraining  many          many
6           ProdCatalogRole              ProdCatalogRole  many          many
7          ProductStoreRole             ProductStoreRole  many          many
8                  Shipment                   ToShipment  many          many
9                  Shipment                 FromShipment  many          many
10     ShipmentRouteSegment  CarrierShipmentRouteSegment  many          many
11                UserLogin                    UserLogin  many          many
12              WebSiteRole                  WebSiteRole  many          many

In [1]:
from sagas.ofbiz.services import OfService as s, oc, track
ok, r=track(lambda a: s().testScv(defaultValue=5.5, message="hello world"))
print(ok, r)

✔ testScv default 21 2019-02-09 17:33:43.804 ➷ 13 ms
True {'responseMessage': 'success', 'resp': 'service done'}

In [6]:
from sagas.ofbiz.entities import OfEntity as e, oc, finder
hub=oc.component('entity_event_hub')
hub.setTrackOn(True)

In [10]:
s().createProductPrice(productId='Test_product_A',
                    productPriceTypeId='AVERAGE_COST',
                    productPricePurposeId='COMPONENT_PRICE',
                    productStoreGroupId='Test_group',
                    currencyUomId='USD',
                    price=oc.j.BigDecimal(50),
                    fromDate=oc.j.Timestamp.valueOf('2013-07-04 00:00:00'))

(False,
 {'fromDate': JavaObject id=o403, 'errorMessageList': ['Exception thrown while creating the "newEntity" GenericValue: org.apache.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:ProductPrice][createdByUserLogin,system(java.lang.String)][createdDate,2019-02-09 19:19:20.32(java.sql.Timestamp)][createdStamp,2019-02-09 19:19:20.32(java.sql.Timestamp)][createdTxStamp,2019-02-09 19:19:20.268(java.sql.Timestamp)][currencyUomId,USD(java.lang.String)][fromDate,2013-07-04 00:00:00.0(java.sql.Timestamp)][lastModifiedByUserLogin,system(java.lang.String)][lastModifiedDate,2019-02-09 19:19:20.32(java.sql.Timestamp)][lastUpdatedStamp,2019-02-09 19:19:20.32(java.sql.Timestamp)][lastUpdatedTxStamp,2019-02-09 19:19:20.268(java.sql.Timestamp)][price,50(java.math.BigDecimal)][productId,Test_product_A(java.lang.String)][productPricePurposeId,COMPONENT_PRICE(java.lang.String)][productPriceTypeId,AVERAGE_COST(java.lang.String)][productStoreGroupId,Test_group(java.lang.String)] (SQL Exception while executing the following:INSERT INTO PRODUCT_PRICE (PRODUCT_ID, PRODUCT_PRICE_TYPE_ID, PRODUCT_PRICE_PURPOSE_ID, CURRENCY_UOM_ID, PRODUCT_STORE_GROUP_ID, FROM_DATE, THRU_DATE, PRICE, TERM_UOM_ID, CUSTOM_PRICE_CALC_SERVICE, PRICE_WITHOUT_TAX, PRICE_WITH_TAX, TAX_AMOUNT, TAX_PERCENTAGE, TAX_AUTH_PARTY_ID, TAX_AUTH_GEO_ID, TAX_IN_PRICE, CREATED_DATE, CREATED_BY_USER_LOGIN, LAST_MODIFIED_DATE, LAST_MODIFIED_BY_USER_LOGIN, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (Duplicate entry \'Test_product_A-AVERAGE_COST-COMPONENT_PRICE-USD-Test_group-2013-\' for key \'PRIMARY\')) (Error while inserting: [GenericEntity:ProductPrice][createdByUserLogin,system(java.lang.String)][createdDate,2019-02-09 19:19:20.32(java.sql.Timestamp)][createdStamp,2019-02-09 19:19:20.32(java.sql.Timestamp)][createdTxStamp,2019-02-09 19:19:20.268(java.sql.Timestamp)][currencyUomId,USD(java.lang.String)][fromDate,2013-07-04 00:00:00.0(java.sql.Timestamp)][lastModifiedByUserLogin,system(java.lang.String)][lastModifiedDate,2019-02-09 19:19:20.32(java.sql.Timestamp)][lastUpdatedStamp,2019-02-09 19:19:20.32(java.sql.Timestamp)][lastUpdatedTxStamp,2019-02-09 19:19:20.268(java.sql.Timestamp)][price,50(java.math.BigDecimal)][productId,Test_product_A(java.lang.String)][productPricePurposeId,COMPONENT_PRICE(java.lang.String)][productPriceTypeId,AVERAGE_COST(java.lang.String)][productStoreGroupId,Test_group(java.lang.String)] (SQL Exception while executing the following:INSERT INTO PRODUCT_PRICE (PRODUCT_ID, PRODUCT_PRICE_TYPE_ID, PRODUCT_PRICE_PURPOSE_ID, CURRENCY_UOM_ID, PRODUCT_STORE_GROUP_ID, FROM_DATE, THRU_DATE, PRICE, TERM_UOM_ID, CUSTOM_PRICE_CALC_SERVICE, PRICE_WITHOUT_TAX, PRICE_WITH_TAX, TAX_AMOUNT, TAX_PERCENTAGE, TAX_AUTH_PARTY_ID, TAX_AUTH_GEO_ID, TAX_IN_PRICE, CREATED_DATE, CREATED_BY_USER_LOGIN, LAST_MODIFIED_DATE, LAST_MODIFIED_BY_USER_LOGIN, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (Duplicate entry \'Test_product_A-AVERAGE_COST-COMPONENT_PRICE-USD-Test_group-2013-\' for key \'PRIMARY\')))'], 'responseMessage': 'error'})

In [11]:
from sagas.ofbiz.entities import OfEntity as e, format
from sagas.ofbiz.services import OfService as s, oc
format(e().getProductPrice(productId="Test_product_A",
                   productPriceTypeId='AVERAGE_COST',
                   productPricePurposeId='COMPONENT_PRICE',
                   productStoreGroupId='Test_group',
                   currencyUomId='USD',
                   fromDate=oc.j.Timestamp.valueOf('2013-07-04 00:00:00')))

+-------------------------+-------------------------+
| name                    | value                   |
|-------------------------+-------------------------|
| taxInPrice              |                         |
| termUomId               |                         |
| priceWithTax            |                         |
| createdStamp            | 2019-02-09 17:12:12.842 |
| productStoreGroupId     | Test_group              |
| taxAuthPartyId          |                         |
| lastModifiedByUserLogin | system                  |
| customPriceCalcService  |                         |
| price                   | 50.000                  |
| taxAuthGeoId            |                         |
| productPricePurposeId   | COMPONENT_PRICE         |
| createdByUserLogin      | system                  |
| lastUpdatedStamp        | 2019-02-09 17:12:12.842 |
| productId               | Test_product_A          |
| lastModifiedDate        | 2019-02-09 17:12:12.818 |
| createdTxStamp          | 2019-02-09 17:12:12.732 |
| taxPercentage           |                         |
| lastUpdatedTxStamp      | 2019-02-09 17:12:12.732 |
| thruDate                |                         |
| fromDate                | 2013-07-04 00:00:00.0   |
| currencyUomId           | USD                     |
| createdDate             | 2019-02-09 17:12:12.818 |
| priceWithoutTax         |                         |
| taxAmount               |                         |
| productPriceTypeId      | AVERAGE_COST            |
+-------------------------+-------------------------+

In [8]:
s().updateProductPrice(
    productId='Test_product_C',
    productPriceTypeId='AVERAGE_COST',
    productPricePurposeId='COMPONENT_PRICE',
    productStoreGroupId='Test_group',
    currencyUomId='USD',
    price=oc.j.BigDecimal(50),
    fromDate=oc.j.Timestamp.valueOf('2013-07-04 00:00:00'))

(True, {'responseMessage': 'success', 'oldPrice': Decimal('20.000')})

In [9]:
s().deleteProductPrice(productId='Test_product_C',
    productPriceTypeId='AVERAGE_COST',
    productPricePurposeId='COMPONENT_PRICE',
    productStoreGroupId='Test_group',
    currencyUomId='USD',
    fromDate=oc.j.Timestamp.valueOf('2013-07-04 00:00:00'))

(True, {'responseMessage': 'success', 'oldPrice': Decimal('50.000')})

In [15]:
ret=(e().getProductPrice(productId="Test_product_C",
                   productPriceTypeId='AVERAGE_COST',
                   productPricePurposeId='COMPONENT_PRICE',
                   productStoreGroupId='Test_group',
                   currencyUomId='USD',
                   fromDate=oc.j.Timestamp.valueOf('2013-07-04 00:00:00')))
print(ret)

None