In [3]:
from sagas.ofbiz.services import OfService as s
from sagas.ofbiz.entities import OfEntity as e

e('meta').FixedAsset

   internal                    name primary             type       field type
0                      fixedAssetId       *               id               id
1                  fixedAssetTypeId                       id               id
2                parentFixedAssetId                       id               id
3               instanceOfProductId                       id               id
4                       classEnumId                       id               id
5                           partyId                       id               id
6                        roleTypeId                       id               id
7                    fixedAssetName                     name             name
8                    acquireOrderId                       id               id
9             acquireOrderItemSeqId                       id               id
10                     dateAcquired                date-time        date-time
11                 dateLastServiced                date-time        date-time
12                  dateNextService                date-time        date-time
13                expectedEndOfLife                     date             date
14                  actualEndOfLife                     date             date
15               productionCapacity              fixed-point      fixed-point
16                            uomId                       id               id
17                       calendarId                       id               id
18                     serialNumber             long-varchar     long-varchar
19              locatedAtFacilityId                       id               id
20           locatedAtLocationSeqId                       id               id
21                     salvageValue          currency-amount  currency-amount
22                     depreciation          currency-amount  currency-amount
23                     purchaseCost          currency-amount  currency-amount
24                purchaseCostUomId                       id               id
25        *        lastUpdatedStamp                date-time        date-time
26        *      lastUpdatedTxStamp                date-time        date-time
27        *            createdStamp                date-time        date-time
28        *          createdTxStamp                date-time        date-time

In [2]:
e('meta').FixedAssetRegistration

   internal                name primary          type    field type
0                  fixedAssetId       *            id            id
1                      fromDate       *     date-time     date-time
2                      thruDate             date-time     date-time
3              registrationDate             date-time     date-time
4              govAgencyPartyId                    id            id
5            registrationNumber          long-varchar  long-varchar
6                 licenseNumber          long-varchar  long-varchar
7         *    lastUpdatedStamp             date-time     date-time
8         *  lastUpdatedTxStamp             date-time     date-time
9         *        createdStamp             date-time     date-time
10        *      createdTxStamp             date-time     date-time

In [12]:
e('meta').FixedAssetMeter

   internal                 name primary         type   field type
0                   fixedAssetId       *           id           id
1             productMeterTypeId       *           id           id
2                    readingDate       *    date-time    date-time
3                     meterValue          fixed-point  fixed-point
4            readingReasonEnumId                   id           id
5                 maintHistSeqId                   id           id
6                   workEffortId                   id           id
7         *     lastUpdatedStamp            date-time    date-time
8         *   lastUpdatedTxStamp            date-time    date-time
9         *         createdStamp            date-time    date-time
10        *       createdTxStamp            date-time    date-time

In [2]:
from sagas.util.name_util import to_global_id, from_global_id
token=to_global_id('FixedAsset','test1')
print(token)
print(from_global_id(token))

Rml4ZWRBc3NldDp0ZXN0MQ==
('FixedAsset', 'test1')

In [13]:
from sagas.ofbiz.services import OfService as s, oc
ok,r=s().createFixedAssetRegistration(
    fixedAssetId='DEMO_VEHICLE_01',
    licenseNumber='123456',
    registrationNumber='123456',
    registrationDate=oc.j.Timestamp.valueOf('2009-12-24 12:33:23.703'),
    fromDate=oc.j.Timestamp.valueOf('2009-12-24 12:33:08.247'),
    thruDate=oc.j.Timestamp.valueOf('2010-12-25 12:33:18.365'))
print(ok,r)

False {'errorMessage': 'Value found (with ids DEMO_VEHICLE_01::2009-12-24 12:33:08.247), cannot create a new one', 'responseMessage': 'error', 'successMessage': None}

In [14]:
from sagas.ofbiz.entities import OfEntity as e, format
fixedAssetRegistration=e().getFixedAssetRegistration(fixedAssetId='DEMO_VEHICLE_01',
                             fromDate=oc.j.Timestamp.valueOf('2009-12-24 12:33:08.247'))
format(fixedAssetRegistration)

+--------------------+-------------------------+
| name               | value                   |
|--------------------+-------------------------|
| fromDate           | 2009-12-24 12:33:08.247 |
| lastUpdatedStamp   | 2019-03-01 23:00:18.578 |
| registrationNumber | 123456                  |
| createdTxStamp     | 2019-03-01 23:00:18.431 |
| createdStamp       | 2019-03-01 23:00:18.578 |
| registrationDate   | 2009-12-24 12:33:23.703 |
| fixedAssetId       | DEMO_VEHICLE_01         |
| lastUpdatedTxStamp | 2019-03-01 23:00:18.431 |
| licenseNumber      | 123456                  |
| govAgencyPartyId   |                         |
| thruDate           | 2010-12-25 12:33:18.365 |
+--------------------+-------------------------+

In [15]:
e('df').listFixedAsset()

,purchaseCostUomId,createdStamp,partyId,lastUpdatedStamp,roleTypeId,purchaseCost,fixedAssetTypeId,fixedAssetName,createdTxStamp,lastUpdatedTxStamp,calendarId,fixedAssetId,parentFixedAssetId,instanceOfProductId
0,None,2019-02-12 19:23:59.290,DEMO_COMPANY,2019-02-12 19:23:59.290,INTERNAL_ORGANIZATIO,NaN,REAL_ESTATE,None,2019-02-12 19:23:58.705,2019-02-12 19:23:58.705,None,1000,None,None
1,USD,2019-01-26 21:09:19.562,None,2019-01-26 21:09:19.562,None,200.0,PRODUCTION_EQUIPMENT,Demo Book,2019-01-26 21:09:19.516,2019-01-26 21:09:19.516,DEMO_CALENDAR,DEMO_BOOK,DEMO_BOOK_GROUP,None
2,None,2019-01-26 21:09:19.558,None,2019-01-26 21:09:19.558,None,NaN,GROUP_EQUIPMENT,Demo Book Group,2019-01-26 21:09:19.516,2019-01-26 21:09:19.516,None,DEMO_BOOK_GROUP,None,None
3,USD,2019-01-26 21:09:19.545,None,2019-01-26 21:09:19.545,None,7000.0,PRODUCTION_EQUIPMENT,Demo Food,2019-01-26 21:09:19.516,2019-01-26 21:09:19.516,DEMO_CALENDAR,DEMO_FOOD,DEMO_FOOD_GROUP,None
4,None,2019-01-26 21:09:19.543,None,2019-01-26 21:09:19.543,None,NaN,GROUP_EQUIPMENT,Demo Food Group,2019-01-26 21:09:19.516,2019-01-26 21:09:19.516,None,DEMO_FOOD_GROUP,None,None
5,USD,2019-01-26 21:09:21.667,None,2019-01-26 21:09:21.667,None,1500.0,EQUIPMENT,Forklift #1,2019-01-26 21:09:19.636,2019-01-26 21:09:19.636,None,DEMO_FORKLIFT_01,None,FORKLIFT_PROPANE
6,USD,2019-01-26 21:09:21.669,None,2019-01-26 21:09:21.669,None,2000.0,EQUIPMENT,Forklift #2,2019-01-26 21:09:19.636,2019-01-26 21:09:19.636,None,DEMO_FORKLIFT_02,None,FORKLIFT_BATTERY
7,USD,2019-01-26 21:09:21.677,None,2019-01-26 21:09:21.677,None,6000.0,EQUIPMENT,HVAC Unit - First Floor,2019-01-26 21:09:19.636,2019-01-26 21:09:19.636,None,DEMO_HVAC_01,None,HVAC_UNIT
8,USD,2019-01-26 21:09:21.680,None,2019-01-26 21:09:21.680,None,6000.0,EQUIPMENT,HVAC Unit - Second Floor,2019-01-26 21:09:19.636,2019-01-26 21:09:19.636,None,DEMO_HVAC_02,None,HVAC_UNIT
9,USD,2019-01-26 21:09:19.541,None,2019-01-26 21:09:19.541,None,50000.0,PRODUCTION_EQUIPMENT,Demo Machine,2019-01-26 21:09:19.516,2019-01-26 21:09:19.516,DEMO_CALENDAR,DEMO_MACHINE,DEMO_MACHINE_GROUP,None

In [16]:
from sagas.ofbiz.services import OfService as s, oc, search_service
search_service('fixedasset')

['addFixedAssetProduct',
 'calculateFixedAssetDepreciation',
 'cancelFixedAssetStdCost',
 'checkUpdateFixedAssetDepreciation',
 'createAcctgTransForFixedAssetMaintIssuance',
 'createFixedAsset',
 'createFixedAssetAndLinkToProduct',
 'createFixedAssetAttribute',
 'createFixedAssetDepMethod',
 'createFixedAssetGeoPoint',
 'createFixedAssetIdent',
 'createFixedAssetIdentType',
 'createFixedAssetMaint',
 'createFixedAssetMaintOrder',
 'createFixedAssetMeter',
 'createFixedAssetProductType',
 'createFixedAssetRegistration',
 'createFixedAssetStdCost',
 'createFixedAssetStdCostType',
 'createFixedAssetType',
 'createFixedAssetTypeAttr',
 'createFixedAssetTypeGlAccount',
 'createPartyFixedAssetAssignment',
 'createWorkEffortFixedAssetAssign',
 'createWorkEffortFixedAssetStd',
 'deleteFixedAssetAttribute',
 'deleteFixedAssetDepMethod',
 'deleteFixedAssetGeoPoint',
 'deleteFixedAssetIdentType',
 'deleteFixedAssetMaint',
 'deleteFixedAssetMaintOrder',
 'deleteFixedAssetMeter',
 'deleteFixedAssetProductType',
 'deleteFixedAssetRegistration',
 'deleteFixedAssetStdCostType',
 'deleteFixedAssetType',
 'deleteFixedAssetTypeAttr',
 'deleteFixedAssetTypeGlAccount',
 'deletePartyFixedAssetAssignment',
 'fixedAssetDepCalcInterface',
 'fixedAssetPermissionCheck',
 'getProductFirstRelatedFixedAsset',
 'issueInventoryItemToFixedAssetMaint',
 'removeFixedAssetIdent',
 'removeFixedAssetProduct',
 'removeWorkEffortFixedAssetAssign',
 'removeWorkEffortFixedAssetStd',
 'returnInventoryItemIssuedToFixedAssetMaint',
 'setWorkEffortFixedAssetAssign',
 'updateFixedAsset',
 'updateFixedAssetAttribute',
 'updateFixedAssetDepMethod',
 'updateFixedAssetGeoPoint',
 'updateFixedAssetIdent',
 'updateFixedAssetIdentType',
 'updateFixedAssetMaint',
 'updateFixedAssetMeter',
 'updateFixedAssetProduct',
 'updateFixedAssetProductType',
 'updateFixedAssetRegistration',
 'updateFixedAssetStdCost',
 'updateFixedAssetStdCostType',
 'updateFixedAssetType',
 'updateFixedAssetTypeAttr',
 'updateFixedAssetTypeGlAccount',
 'updatePartyFixedAssetAssignment',
 'updateWorkEffortFixedAssetAssign',
 'updateWorkEffortFixedAssetStd']

In [17]:
e('meta').FixedAssetProduct

   internal                     name primary         type   field type
0                       fixedAssetId       *           id           id
1                          productId       *           id           id
2            fixedAssetProductTypeId       *           id           id
3                           fromDate       *    date-time    date-time
4                           thruDate            date-time    date-time
5                           comments              comment      comment
6                        sequenceNum              numeric      numeric
7                           quantity          fixed-point  fixed-point
8                      quantityUomId                   id           id
9         *         lastUpdatedStamp            date-time    date-time
10        *       lastUpdatedTxStamp            date-time    date-time
11        *             createdStamp            date-time    date-time
12        *           createdTxStamp            date-time    date-time